# Generated by Django 4.0.5 on 2022-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_cover', models.FileField(null=True, upload_to='case')),
                ('case_name', models.CharField(max_length=50)),
                ('case_desc', models.TextField(default='No Case Description added yet.', max_length=1000)),
                ('case_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
